// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIWgrpJJWFb7hv2q6_Ds2TP-fWnb1g2Rw',
    appId: '1:301804468407:web:c2daaf81684d8b9e003532',
    messagingSenderId: '301804468407',
    projectId: 'netflix-clone-test-7ded9',
    authDomain: 'netflix-clone-test-7ded9.firebaseapp.com',
    storageBucket: 'netflix-clone-test-7ded9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAazSlIzITe5eQa34UrRKaDY-18K8pLmDw',
    appId: '1:301804468407:android:287617595e19c96d003532',
    messagingSenderId: '301804468407',
    projectId: 'netflix-clone-test-7ded9',
    storageBucket: 'netflix-clone-test-7ded9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOhiGv-FFj1mCVJ9i0enmY3nEglX7vxQ',
    appId: '1:301804468407:ios:ea5f113bf4d2c91b003532',
    messagingSenderId: '301804468407',
    projectId: 'netflix-clone-test-7ded9',
    storageBucket: 'netflix-clone-test-7ded9.appspot.com',
    iosClientId: '301804468407-9pvdpiskp7n58es0i5a4crf0o2l2td1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOhiGv-FFj1mCVJ9i0enmY3nEglX7vxQ',
    appId: '1:301804468407:ios:ea5f113bf4d2c91b003532',
    messagingSenderId: '301804468407',
    projectId: 'netflix-clone-test-7ded9',
    storageBucket: 'netflix-clone-test-7ded9.appspot.com',
    iosClientId: '301804468407-9pvdpiskp7n58es0i5a4crf0o2l2td1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );
}
